### Ad Strategy Optimization using Thompson Sampling

In [8]:
# AI for Sales & Advertizing - Sell like the Wolf of AI Street
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import random

N = 10000
d = 9

conversion_rates = [0.05, 0.13, 0.09, 0.16, 0.11, 0.04, 0.20, 0.08, 0.01]
dataset = np.zeros((N, d-1))

for i in range(N):
    for j in range(d-1):
        if np.random.rand() <= conversion_rates[j]:
            dataset[i, j] = 1

print(dataset)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
